runtime: nodejs20

env_variables:
  NODE_ENV: production
  PORT: 8080
  CLIENT_URL: https://finalproject-462406.uc.r.appspot.com
  DATABASE_URL: postgresql://[USERNAME]:[PASSWORD]@localhost/[DB_NAME]?host=/cloudsql/[PROJECT_ID]:[ZONE]:[DB_NAME]
  GEMINI_API_KEY: api_key_here
  GOOGLE_CLIENT_ID: client_id_here
  GOOGLE_CLIENT_SECRET: client_secret_here
  SESSION_SECRET: session_secret_here

beta_settings:
  cloud_sql_instances: [PROJECT_ID]:[ZONE]:[DB_NAME]

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

entrypoint: npm start
