name: Deploy to Google App Engine

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install
        cd server && npm install
        cd ../client && npm install
    
    - name: Build client
      run: cd client && npm run build
    
    - name: Generate Prisma client
      run: cd server && npx prisma generate
    
    - name: Run tests (if available)
      run: |
        cd client && npm test -- --coverage --watchAll=false || true
        cd ../server && npm test || true

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    # Install the gcloud SDK (already authenticated by the step above)
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: '${{ secrets.GCP_PROJECT_ID }}'

    # Node & build steps
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies & build
      run: |
        npm ci
        npm --prefix server ci
        npm --prefix client ci
        npm run build        # builds React into client/build
        npx prisma generate --schema=server/prisma/schema.prisma

    - name: Deploy to App Engine
      run: |
        gcloud app deploy app.yaml --quiet --promote --stop-previous-version 